name: tests

on:
  push:
    branches: ["main", "workflows"]
  pull_request:
    branches: ["main"]

jobs:
  run_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        openresty_version:
          - 1.27.1.2
          - 1.25.3.2
          - 1.21.4.4
          - 1.19.9.2

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - name: Install dependencies of OpenResty on macOS
      if: ${{ matrix.os == 'macos-latest' && ! startsWith( matrix.openresty_version, '1.27') }}
      run: |
        brew install pcre
        sudo mkdir -p -m 0777 /usr/local/include && ln -s /opt/homebrew/include/* /usr/local/include
        sudo mkdir -p -m 0777 /usr/local/lib && ln -s /opt/homebrew/lib/* /usr/local/lib

    - name: Install OpenResty
      uses: leafo/gh-actions-openresty@v2
      with:
        openrestyVersion: ${{ matrix.openresty_version }}

    - name: Test OpenResty
      run: resty -v && resty -e 'print("Hello, OpenResty v${{ matrix.openresty_version }}!")'

    - name: Install CPAN
      run: curl -s -L http://cpanmin.us/ > /usr/local/bin/cpanm && chmod +x /usr/local/bin/cpanm

    - name: Install Test::Nginx
      run: cpanm -S -q -n Test::Nginx

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Start Redis on Ubuntu
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: supercharge/redis-github-action@1.8.0
      with:
        redis-version: 5

    - name: Install and start Redis on macOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew install redis@6.2 && brew services start redis@6.2

    - name: Run tests
      run: TEST_NGINX_BINARY=/usr/local/openresty/bin/openresty prove -r t/ || ( cat error.log && exit 1 )
